name: llm_serve
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.12
  - pip
  - setuptools
  - ipykernel
  - pip: 
    - fastapi
    - transformers
    - torch 
    - fastapi 
    - uvicorn
    - streamlit 
    - requests
    - accelerate
    - bitsandbytes
